We are disabling the caching for now until we can log into the machine directly and enable it.
See IRC conversation here:
http://logs.glob.uno/?c=mozilla%23servo#c424015

Here is an example of the errors:

```
New python executable in /c/buildbot/slave/windows/build/python/_virtualenv/bin/python2.7
Also creating executable in /c/buildbot/slave/windows/build/python/_virtualenv/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python2.7
looking for rustc at /c/buildbot/slave/windows/build/C:\msys64\home\Administrator\.servo/rust/2016-04-29/rustc-nightly-x86_64-pc-windows-gnu/rustc/bin/rustc
Error running mach:

    ['build', '-d', '-v']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory: '/c/buildbot/slave/windows/build/C:\\msys64\\home\\Administrator\\.servo'

  File "/c/buildbot/slave/windows/build/python/servo/build_commands.py", line 195, in build
    self.ensure_bootstrapped(target=target)
  File "./python/servo/command_base.py", line 432, in ensure_bootstrapped
    Registrar.dispatch("bootstrap-rust", context=self.context, target=filter(None, [target]))
  File "/c/buildbot/slave/windows/build/python/_virtualenv/lib/python2.7/site-packages/mach/registrar.py", line 123, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/c/buildbot/slave/windows/build/python/_virtualenv/lib/python2.7/site-packages/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
  File "/c/buildbot/slave/windows/build/python/servo/bootstrap_commands.py", line 146, in bootstrap_rustc
    os.makedirs(rust_dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
program finished with exit code 1
elapsedTime=30.809000
```